const Constants={
    CREATE_TASK:'CREATE_TASK',
    REMOVE_TASK:'REMOVE_TASK',
    MARK_TASK_AS_COMPLETE:'MARK_TASK_AS_COMPLETE',
    LOAD_TODOS_IN_PROGRESS:'LOAD_TODOS_IN_PROGRESS',
    LOAD_TODOS_SUCCESS:'LOAD_TODOS_SUCCESS',
    LOAD_TODOS_FAILURE:'LOAD_TODOS_FAILURE'
}

export default Constants;